const display=document.querySelector('#display');let expression='';
function render(value=expression||'0'){display.textContent=value.replaceAll('*','×').replaceAll('/','÷');}
function append(value){expression+=value;render();}
function clear(){expression='';render();}
function backspace(){expression=expression.slice(0,-1);render();}
function tokenize(source){const tokens=[];let number='';for(const char of source.replaceAll(' ','')){if(/[0-9.]/.test(char)){number+=char;continue}if(number){if((number.match(/\./g)||[]).length>1)throw new Error();tokens.push(Number(number));number=''}if('+-*/()'.includes(char))tokens.push(char);else throw new Error()}if(number){if((number.match(/\./g)||[]).length>1)throw new Error();tokens.push(Number(number))}return tokens;}
function evaluate(source){const tokens=tokenize(source);let i=0;function primary(){const token=tokens[i++];if(typeof token==='number'){if(!Number.isFinite(token))throw new Error();return token}if(token==='('){const value=sum();if(tokens[i++]!==')')throw new Error();return value}if(token==='-')return-primary();if(token==='+')return primary();throw new Error()}function product(){let value=primary();while(tokens[i]==='*'||tokens[i]==='/'){const op=tokens[i++],right=primary();value=op==='*'?value*right:value/right}return value}function sum(){let value=product();while(tokens[i]==='+'||tokens[i]==='-'){const op=tokens[i++],right=product();value=op==='+'?value+right:value-right}return value}const result=sum();if(i!==tokens.length||!Number.isFinite(result))throw new Error();return result}
function calculate(){if(!expression.trim())return;try{const result=evaluate(expression);expression=String(Math.round((result+Number.EPSILON)*1e10)/1e10);render()}catch{expression='';render('Erro')}}
document.querySelector('.keys').addEventListener('click',e=>{const button=e.target.closest('button');if(!button)return;if(button.dataset.value)append(button.dataset.value);if(button.dataset.action==='clear')clear();if(button.dataset.action==='backspace')backspace();if(button.dataset.action==='calculate')calculate()});
addEventListener('keydown',e=>{if(/[0-9.+\-*/()]/.test(e.key)&&e.key.length===1)append(e.key);else if(e.key==='Enter'||e.key==='=')calculate();else if(e.key==='Backspace')backspace();else if(e.key==='Escape')clear()});render();